### ISSUE TITLE
fun okhttp3.Call.await() = TODO() ?

### ISSUE THREAD

**Issue by jmfayard** [gildor/kotlin-coroutines-retrofit#11]
Hello

I just [gave a try](https://github.com/jmfayard/skripts/blob/fd3e8cea68a9f40762a11fccc24e749014626970/test/kotlin/retrofit-coroutines.kt#L30-L63) to your library and found it very handy.

I often have to mix retofit and okhttp3 calls inside the same project and I was thinking it would make a lot of sense to have those await extension functions for okhttp as well.

Since retrofit requires okhttp3, that would not add a new dependancy for the users of the library

A use case would be

```kotlin
val retrofitData = api.getData().await()
val okRequest = createRequest(retrofitData.url)
val okData = okClient.newCall(okRequest).await()
```

**Comment by gildor** [comment]
@jmfayard Hi. I had an idea to support okhttp too, but I think it should be separate library because it can be used without retrofit dependency.
Do you have any good use cases for coroutines in OkHttp instead `Call<T>.await()`?

**Comment by jmfayard** [comment]
`retrofit` without any additional dependancy is actually a lean library. 
How many people would use both okhttp and your library and would mind to have a dependancy to retrofit ? IMHO not enough that you should care about it, at least for now.

As for the API, okhttp3.Call  and retrofit2.Call are basically identical, so I guess the same would work

**Comment by gildor** [comment]
No, I'm talking about people who want to use okhttp without retrofit and use coroutines extensions

**Comment by gildor** [comment]
@jmfayard I've started work on OkHttp, and for now, I see the only case is await() for Call
Library not published yet, but that is only one extension function - https://github.com/gildor/kotlin-coroutines-okhttp

**Comment by gildor** [comment]
Closing task. Please create issue about OkHttp there https://github.com/gildor/kotlin-coroutines-okhttp
