### ISSUE TITLE
Checking for continuation.isCancelled only in failures 

### ISSUE THREAD

**Issue by robertoestivill** [gildor/kotlin-coroutines-retrofit#20]
I have just noticed that the methods in `CallAwait.kt` only check if the `continuation.isCancelled` on the `onFailure` callback. Is there any reason why `onResponse` doesn't implement the same behavior ? 

```java
override fun onFailure(call: Call<T>, t: Throwable) {
    // Don't bother with resuming the continuation if it is already cancelled.
    if (continuation.isCancelled) return
    ...
}
```

**Comment by NightlyNexus** [comment]
The contract of OkHttp's Call.Factory requires canceled calls to call onFailure. OkHttpClient obeys this.
onResponse won't be called for canceled calls.

**Comment by robertoestivill** [comment]
Thanks for the clarification @NightlyNexus
