### ISSUE TITLE
Handling Call<Unit>

### ISSUE THREAD

**Issue by k-kagurazaka** [gildor/kotlin-coroutines-retrofit#22]
Hello, I have a question.
Some my APIs return "204: NO CONTENT" so I handle it by Retrofit like:

```kotlin
fun myApi(): Call<Unit>
```

In this case, `myApi().await()` throws NPE since the response body is always `null`.
How to solve the problem?
Thanks.

**Comment by gildor** [comment]
You have a few options, one of them to add  custom type adapter to your
json mapping library that returns Unit instance instead null. I think this
is the most correct way to do that. Also you can add retrofit converter
factory for that, but if you already use gson/Moshi converter factor y,
then better to add custom type adapter.
Also you can use awaitResponse() instead

**Comment by k-kagurazaka** [comment]
@gildor 
Thanks for your quick reply.
Your idea looks good. I'll try it.

Thanks again!

**Comment by LouisCAD** [comment]
Hi @k-kagurazaka,
Did you ended up writing some code to handle `Call<Unit>` with Moshi or something else?

**Comment by LouisCAD** [comment]
Hi @gildor,
I wrote a snippet to allow it with a method named `awaitSuccess()` that returns `Unit` on `Call<Void>` methods. Tell me what you think about it and if I should submit a PR.

```kotlin
/**
 * Suspend extension that allows suspend [Call] inside coroutine.
 *
 * @return [Unit] or throw exception
 */
public suspend fun Call<Void>.awaitSuccess() {
    return suspendCancellableCoroutine { continuation ->
        enqueue(object : Callback<Void> {
            override fun onResponse(call: Call<Void>?, response: Response<Void>) {
                if (response.isSuccessful) {
                    val body = response.body()
                    continuation.resume(Unit)
                } else {
                    continuation.resumeWithException(HttpException(response))
                }
            }

            override fun onFailure(call: Call<Void>, t: Throwable) {
                // Don't bother with resuming the continuation if it is already cancelled.
                if (continuation.isCancelled) return
                continuation.resumeWithException(t)
            }
        })

        registerOnCompletion(continuation)
    }
}
```
If anyone want to try it in his project, you'll also need the following method which is private in the library:

```kotlin
private fun Call<*>.registerOnCompletion(continuation: CancellableContinuation<*>) {
    continuation.invokeOnCompletion {
        if (continuation.isCancelled)
            try {
                cancel()
            } catch (ex: Throwable) {
                //Ignore cancel exception
            }
    }
}
```

**Comment by k-kagurazaka** [comment]
@LouisCAD 
I tried to create a Gson TypeAdapter but it doesn't work since Gson skip to pass null response to TypeAdapters.
Currently, I write an extension function `awaitUnit()` almost same as you post above.

**Comment by JakeWharton** [comment]
Neither of those are the correct solution. See
https://github.com/square/retrofit/issues/2329#issuecomment-301316873 to
support Unit and then neither the chosen converter nor anything that deals
with call adapters has to change.

**Comment by gildor** [comment]
@LouisCAD I'm against including such ad hoc API to this library, it's not kotlin-coroutines-retrofit specific problem and shouldn't be a part of API.
The best solution, of course: add support for `Unit` to Retrofit, as Jake mentioned.

A solution, based on type adapter maybe not the best, but still, it covers some cases of Gson usage, including the case of Retrofit:

I use this Unit type adapter for Gson.
```kotlin
class UnitAdapter : JsonSerializer<Unit>, JsonDeserializer<Unit> {

    override fun serialize(src: Unit?, typeOfSrc: Type?, context: JsonSerializationContext?): JsonElement = JsonNull.INSTANCE

    override fun deserialize(json: JsonElement?, typeOfT: Type?, context: JsonDeserializationContext?): Unit? = Unit

}
```

**Comment by gildor** [comment]
@LouisCAD Yes, of course, I agree that solution, that covers all Retrofit type adapters is better in case of Retrofit. 

I just  reacted to @k-kagurazaka comment, that it's possible even with null:
> I tried to create a Gson TypeAdapter but it doesn't work since Gson skip to pass null response to TypeAdapters.

And also, Gson can be used without Retrofit, so sometimes you still need adapter for Unit

**Comment by gildor** [comment]
@LouisCAD Agree about Readme, but probably Kotlin section on http://square.github.io/retrofit/ would be a better place for this.
@JakeWharton do you have plans to add Kotlin specific docs to Retrofit website?

**Comment by k-kagurazaka** [comment]
Thanks @gildor .
I had the wrong something.
