### ISSUE TITLE
No Response When Call a Service

### ISSUE THREAD

**Issue by MohamedTaher** [gildor/kotlin-coroutines-retrofit#28]
I use awaitResult method 
```
public fun asyncCreateNewTask(dayPlanTask: DayPlanTask) = runBlocking {
        var state: Status = Status.Error

        val service = InspectionAPI().getInspectionService()

        val result : Result<Reply.Single<DayPlanTask>> = service.createWeeklyPlanTask(dayPlanTask).awaitResult()
        when (result) {
            is Result.Ok -> {
                state = Status.OK
            }
            is Result.Error -> {
                state = Status.InternalServerError
            }
            is Result.Exception -> {
                state = Status.Error
            }
            else -> {
                Log.e("WAIT_TRY", "ELSE branch")
            }
        }

        Log.e("STATE", state.toString())
    }
```
the app is stuck and not responsible, also it's not throwing any exception 
it isn't entered in onResponse and onFailure functions at CallAwait.awaitResult()

**Comment by gildor** [comment]
> the app is stuck and not responsible

`runBlocking` blocks thread and can be used only when it's fine for you, but it's definitely wrong for UI thread. Replace it with `launch(DispatcherOnYourChoice)` where `DispatcherOnYourChoice` can be [UI](https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android) (if you want to touch views inside your coroutine) or any other dispatcher, depending on your case.

> also it's not throwing any exception
I don't see a case when your code could throw an exception. Could you please explain your problem.

Please read Coroutines Guide to UI programming -
 https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md

**Comment by gildor** [comment]
@MohamedTaher I just realized that my examples could be confusing for people who never used coroutines, so I added [a note about `runBlocking` ](https://github.com/gildor/kotlin-coroutines-retrofit/blob/master/README.md#how-to-use) to Readme

**Comment by MohamedTaher** [comment]
Now I use launch(UI) instead of runBlocking  and It's working well 
Thanks a lot
