### ISSUE TITLE
0.8.1 fails to resolve in Gradle where 0.7.1 has no issues

### ISSUE THREAD

**Issue by bajabob** [gildor/kotlin-coroutines-retrofit#31]
For some reason when upgrading to 0.8.1, gradle cannot resolve the JAR from the server. 

> Error:Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve ru.gildor.coroutines:kotlin-coroutines-retrofit:0.8.1.
> <a href="openFile:/../app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@productionDebug/compileClasspath&#39;: Could not resolve ru.gildor.coroutines:kotlin-coroutines-retrofit:0.8.1.">Show Details</a>

**Comment by gildor** [comment]
Hi @bajabob thanks for this issue.
Yeah, this is a problem with pom file in 0.8.1 because now I use implicit Kotlin version for stdlib. I fixed it in 0.8.2. Soon will be published, I will notify you

**Comment by gildor** [comment]
@bajabob Version 0.8.2 with fixed pom released to Jcenter and Maven Central, please check.
Close an issue
