### ISSUE TITLE
No response coming back

### ISSUE THREAD

**Issue by DFreds** [gildor/kotlin-coroutines-retrofit#33]
I'm trying to get a token but nothing is happening. Here is my code:

```
fun handleLogin() {
        println("about to get token")
        launch {
            print("getting token")
            val token = service.getToken(code = code, verifier = verifier).await()
            print("token is $token")
        }
}
```

It prints out the "about to get token" but never prints out the "getting token" nor the "token is $token". I know it's not Retrofit because it works when I use the basic `enqueue` functionality. Any ideas?

**Comment by gildor** [comment]
@DFreds Did you resolve your issue? Maybe application finished before `launch` started

**Comment by DFreds** [comment]
Yeah, all fixed. It was on my end. Thanks!
