### ISSUE TITLE
Support Kotlin 1.3-M2 EAP

### ISSUE THREAD

**Issue by azihsoyn** [gildor/kotlin-coroutines-retrofit#44]
Hi, this is the great plugin!

However, only 1.3-M1 only supported.
https://github.com/gildor/kotlin-coroutines-retrofit/blob/kotlin-1.3/build.gradle.kts

The other day, Kotlin 1.3 EAP M2 has released.
https://blog.jetbrains.com/kotlin/2018/08/kotlin-1-3-m2/

Please support also 1.3-M2.

Thanks.

**Comment by gildor** [comment]
I just released version 0.13.0-eap13 with the support of Kotlin 1.3 RC
Closing
