### ISSUE TITLE
Result.OK value = null

### ISSUE THREAD

**Issue by andysiahaan90** [gildor/kotlin-coroutines-retrofit#46]
when i using .awaitResult(),

i always get result = Result.Ok{value=null null null, response=Response{protocol=http/1.1, code=200, message=OK, url = http://xxxxx)

I don't know why the value is null.
I am using 0.13.0-eap13 version and retrofit 2.5.0 now.

before update, it has value when i am using 0.9.0 version.  please help

**Comment by gildor** [comment]
Value can be null it depends on the request type, for example some responses just don't have body, so value is null in this case
