### ISSUE TITLE
Call cancellation feedback causes crash when coroutine is cancelled

### ISSUE THREAD

**Issue by kingsleyadio** [gildor/kotlin-coroutines-retrofit#8]
Hello.

I've been experiencing a couple of crashes with this library. Spent a lot of time trying to figure out why.
I discovered it was due to this code in `Callback#onFailure`
```kotlin
//if (call.isCanceled) return
/**
 * It is better just to invoke resumeWithException:
 * 1. If the coroutine was cancelled, then resumeWithException is just ignored
 * 2. However, if somebody just invokes Call.cancel(), then we should resume
 *    continuation that was doing `await` on this call, or it'll await forever.
  */
continuation.resumeWithException(t)
```

Basically, if the coroutine is already canceled, and then `continuation.resumeWithException(e)` is called, everything blows up because this exception is different from the one originally held by the coroutine.
A comment from `AbstractCoroutine#resumeWithException` (from kotlinx.coroutine library):
```kotlin
// ignore resumes on cancelled continuation, but handle exception if a different one is here
```

Fixing this is involves simply checking whether the coroutine has been cancelled before attempting to resume with exception

```kotlin
override fun onFailure(call: Call<T>, t: Throwable) {
    if (!cont.isCancelled) cont.resumeWithException(t)
}
```
This is still in line with the 2 comments @elizarov made regarding the resumption:
1. If the coroutine was canceled, we can as well avoid resuming it anymore
2. We still correctly resume continuation if someone invokes `Call#cancel` directly

**Comment by gildor** [comment]
Thanks for detailed description. I'll check and release updated version in one-two days (sorry, now on vacation)

**Comment by kingsleyadio** [comment]
Oh. Thanks for the quick response.
I already submitted a pull request #9 that fixes this. Kindly take a look at it.

**Comment by gildor** [comment]
@kingsleyadio My original code had cancelled state handling, as you can see. Probably something changed from the last review from Roman.
I've merged your PR

**Comment by kingsleyadio** [comment]
Awesome. I look forward to the release!

Yes. I saw that you handled the case where a coroutine cancellation triggered a call cancellation. However, it failed to handle the case where the call itself was cancelled directly.

**Comment by gildor** [comment]
@kingsleyadio Yeah, I got, that it's the case with cancelled coroutine. Thanks. Fixed and released 
https://bintray.com/gildor/maven/kotlin-coroutines-retrofit/0.4.1
Published to Maven Central as well.
